Progress, but....
line 231, in wildsHiLo_step2
  More debugging needed:
hand_view.controller.processed_full_board[k_group] = processed_group
TypeError: 'NoneType' object does not support item assignment